# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*.bb \
            ${LAYERDIR}/recipes-*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-imx6ull-barebones"
BBFILE_PATTERN_meta-imx6ull-barebones = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-imx6ull-barebones = "6"

LAYERDEPENDS_meta-imx6ull-barebones = "core"
LAYERSERIES_COMPAT_meta-imx6ull-barebones = "whinlatter"
